title: Randy Molren
subtitle: Tech
description: Blog of Randy Morlen.

author: Randy Morlen
email: rrmtx07@gmail
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://rmorlen.github.io"

# Social settings
facebook_url: https://www.facebook.com/rmorlen
github_url: https://github.com/rmorlen
linkedin_url: https://www.linkedin.com/in/rmorlen/
twitter_url: https://twitter.com/rmorlen

# SEO settiongs
google_analytics: 

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
